---
title: "MNS et MNT"
output: 
  html: 
    number_sections: true
    toc: true
    code-fold: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = FALSE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```

# Objet

Les images sentinel sont faciles d'accès et permettent d'évaluer les changements récents.


Pour le MNS et le MNT, la campagne LIDAR de l'IGN a permis de récupérer des données beaucoup plus précises.


Le mieux est de repérer les zones et de chercher les dalles sur cartes.gouv.fr


https://geoservices.ign.fr/lidarhd

https://cartes.gouv.fr/telechargement/IGNF_MNT-LIDAR-HD


https://data.geopf.fr/wms-r?SERVICE=WMS&VERSION=1.3.0&EXCEPTIONS=text/xml&REQUEST=GetMap&LAYERS=IGNF_LIDAR-HD_MNS_ELEVATION.ELEVATIONGRIDCOVERAGE.LAMB93&FORMAT=image/geotiff&STYLES=&CRS=EPSG:2154&BBOX=661999.75,6868000.25,662999.75,6869000.25&WIDTH=2000&HEIGHT=2000&FILENAME=LHD_FXX_0662_6869_MNS_O_0M50_LAMB93_IGN69.tif

https://data.geopf.fr/wms-r?SERVICE=WMS&VERSION=1.3.0&EXCEPTIONS=text/xml&REQUEST=GetMap&LAYERS=IGNF_LIDAR-HD_MNT_ELEVATION.ELEVATIONGRIDCOVERAGE.LAMB93&FORMAT=image/geotiff&STYLES=&CRS=EPSG:2154&BBOX=661999.75,6868000.25,662999.75,6869000.25&WIDTH=2000&HEIGHT=2000&FILENAME=LHD_FXX_0662_6869_MNT_O_0M50_LAMB93_IGN69.tif


D'après le nom du fichier, quelle est la précision ?


Charger les 2 dalles

A t on besoin de reprojeter ?


# Couper au carreau manquant

Explorer le menu imagerie / processus et raster functions, quelle est la différence ?

# Symbologie

clic droit au niveau de la fenêtre contenu / symbologie

Rechercher la palette élévation dans le mode continu


Observer les différences avec l'image de départ

# MNH


## Calculatrice raster



## Informations image


Prendre les arbres ou les bâtiments, trouver une fourchette de hauteurs.

Refaire une symbologie


## Tester les modes de visualisation



# Simuler un point d'observation

Comment voir le plus d'arbres ?






