project:
  type: website

website:
  title: "L6ECSIG"
  navbar:
    left:
      - text: "Introduction"
        href: intro.html
      - text: "Données"
        href: 01_TD1.html  
      - text: "Projections"
        href: 02_TD2.html 
      - text: "GT Vecteurs"
        href: 03_TD3.html 
      - text: "GT Rasters"
        href: 04_TD4.html 
      - text: "MNT"
        href: 05_TD5_TT.html 
    right:
      - icon: fa-github
        href: https://github.com/beababa/beababa.github.io
        
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

editor: visual

