project:
  type: website

website:
  title: "cours L6ECSIG"
  navbar:
    left:
      - text: "Introduction"
        href: intro.html
      - text: "Données"
        href: 01_TD1.html
      - text: "Bases R"
        href: 03_basesR.html 
      - text: "R spatial"
        href: 04_Rspatial.html
      - text: "Correction"
        href: 05_correction.html 
      - text: "Donnees"
        href: 06_Donnees.html 
      - text: "Traitement"
        href: 07_traitement.html   
      - text: "Resultat"
        href: 08_resultat.html   

      - about.qmd
    right:
      - icon: fa-github
        href: https://github.com/beababa/beababa.github.io
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

editor: visual

