---
title: "Tableau"
output: 
  html: 
    number_sections: true
    toc: true
    code-fold: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = FALSE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```

# Objet

Tableau des problématiques

+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| TD | étudiants     | nom et ville              | problématique                                                                                      | remarque                                                    |
+====+===============+===========================+====================================================================================================+=============================================================+
| 6  | Nathan        | Antony et Clamart         | Proximité et similarité                                                                            |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    | Jeanne M      |                           | comment s'organise richesse et pauvreté                                                            |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|    | Adeèle        | Bzh                       | périurbanisation dans l'aire urbaine de Nantes                                                     |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    | Jeanne V      |                           | distance au centre                                                                                 |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|    | Iudig         | Martinique                | Comment représenter la pauvreté en Martinique (réalité plus complexe qu'en métropole)              |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    | Mathilde      |                           |                                                                                                    |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|    | Tia           | Le Blanc Mesnil           | ségrégation pauvreté et évolution gentrification                                                   | ne pas oublier l'OFGL                                       |
|    |               |                           |                                                                                                    |                                                             |
|    | Clark         | Saint Ouen                | étalement tissu pavillon / immeuble                                                                |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    |               | Mille Fleurs              |                                                                                                    |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|    | Joachim       |                           | opposition centre / périphérie                                                                     |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    | Toscane       |                           | contrastes, y compris relief                                                                       |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|    | Lylia         | Saint Denis               | Transports en commun et mobilité                                                                   | attention données transports peut-être difficiles à traiter |
|    |               |                           |                                                                                                    |                                                             |
|    |               |                           | inégalités sociales                                                                                |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| 7  |               | Biarritz                  | tourisme et logement, prix terrain m², résidence principale et secondaire, dynamisme des quartiers | pas trop d'ambition attention                               |
|    |               |                           |                                                                                                    |                                                             |
|    |               | Bordeaux                  |                                                                                                    |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|    | Abigaelle     | Aligot Saussice           | ville centre                                                                                       | attention aux données                                       |
|    |               |                           |                                                                                                    |                                                             |
|    | Vadim         |                           | politique commune et logements sociaux                                                             |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|    | Romane Cédric | Calais                    | risques littoraux                                                                                  | transformer la problématique : rajouter du social           |
|    |               |                           |                                                                                                    |                                                             |
|    |               | Dunkerque                 | topographie et POS                                                                                 |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    |               | Wesh la Team              | distance littoral                                                                                  |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|    | Thibault      |                           | Correlation abstention et carreaux niveaux de vie                                                  |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    | Louise        |                           |                                                                                                    |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|    | Richardson    | Le Blanc Mesnil           | Comment les politiques municipales favorisent la gentrification                                    |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    | Trinity       | Saint Ouen                | (bat, transport GPE, démographie, typologie)                                                       |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    |               | The Americans             |                                                                                                    |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|    |               | Saint Denis               | logement et revenus                                                                                |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    |               | Rosny s / Bois            | dimension spatiale, proximité parisienne                                                           |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    |               |                           | raster : densité pop                                                                               |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|    | Adel          | Hauts de Seine            | espaces verts comme marqueur des inégalités                                                        |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    | Simon         |                           | 2 hypothèses : marqueur social direct ou pas                                                       |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    |               |                           | OFGL pour les politiques locales                                                                   |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|    | Jeanne        | Angers et proche banlieue | Centre et prériphérie                                                                              |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    |               | La Loire c'est super      | type activités / vote / occupation du sol (raster)                                                 |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|    |               | Clermont                  | opposition ville riche / pauvre                                                                    |                                                             |
|    |               |                           |                                                                                                    |                                                             |
|    |               | Senlis                    |                                                                                                    |                                                             |
+----+---------------+---------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
